CREATE SCHEMA baseball;
USE baseball;

CREATE TABLE Teams (
TeamID INT NOT NULL, 
TeamName VARCHAR(20),
City VARCHAR(20),
PRIMARY KEY(TeamID)
);
ALTER TABLE Teams ADD COLUMN Abbrev VARCHAR(3);

CREATE TABLE Players (
PlayerID INT NOT NULL,
PlayerName VARCHAR(50),
TeamID INT,
Position VARCHAR(3),
Bats VARCHAR(1),
Throws VARCHAR(1),
Age INT,
PRIMARY KEY(PlayerID),
FOREIGN KEY(TeamID) REFERENCES Teams(TeamID)
);
ALTER TABLE Players ADD COLUMN URL VARCHAR(256);

CREATE TABLE GameLogByPitcher (
GLBPID INT NOT NULL AUTO_INCREMENT,
PlayerID INT NOT NULL,
TeamID INT NOT NULL,
GameDate DATE NOT NULL,
OpponentAbbrev VARCHAR(3),
IsHome BOOLEAN,
W INT,
L INT,
ERA FLOAT,
G INT,
GS INT,
CG INT,
Shutout INT,
Saves INT,
SaveOpp INT,
IP FLOAT,
H INT,
R INT,
ER INT,
HR INT,
HB INT,
BB INT,
IBB INT,
SO INT,
Pitches INT,
Strikes INT,
AVG FLOAT,
WHIP FLOAT,
GOAO FLOAT,
PRIMARY KEY(GLBPID),
FOREIGN KEY(TeamID) REFERENCES Teams(TeamID),
FOREIGN KEY(PlayerID) REFERENCES Players(PlayerID)
);

CREATE TABLE GameLogByBatter (
GLBBID INT NOT NULL AUTO_INCREMENT,
PlayerID INT NOT NULL,
TeamID INT NOT NULL,
GameDate DATE NOT NULL,
OpponentAbbrev VARCHAR(3),
IsHome BOOLEAN,
AB INT,
R INT,
H INT,
TB INT,
Doubles INT,
Triples INT,
HR INT,
RBI INT,
BB INT,
IBB INT,
SO INT,
SB INT, 
CS INT,
BA FLOAT,
OBP FLOAT,
SLG FLOAT,
HBP INT,
SAC INT,
SF INT,
PRIMARY KEY(GLBBID),
FOREIGN KEY(TeamID) REFERENCES Teams(TeamID),
FOREIGN KEY(PlayerID) REFERENCES Players(PlayerID)
);


