"""Fixing SQL

Revision ID: f93147d658d9
Revises: 428eb2e16ba6
Create Date: 2022-08-15 15:57:51.303197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93147d658d9'
down_revision = '428eb2e16ba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
